application/common/constants.py

Implemented Common Methods for retrieving Database, TestClass, Execution Status by Name and Id 

---

application/api/dashboard.py
application/api/data_quality_index.py
application/common/constants.py
application/routes.py

added api  for project DQI, ORG DQI and SideBar Menu

added api  for project DQI, ORG DQI and SideBar Menu

---

application/api/testcase.py
application/common/constants.py
application/common/utils.py
application/routes.py

@lalithbachimanchi @HarshadKavathiya  Please Review the Edit Test Case API

Edit Test Case

---

application/api/login.py
application/common/utils.py
application/routes.py

@HarshadKavathiya @lalithbachimanchi Please Review my code for change password

change password

---

application/api/login.py
application/api/testcase.py
application/common/constants.py
application/common/runbysuiteid.py
application/helper/corefunctions/ddlcheck.py
application/helper/runnerclass.py
application/routes.py

Develop token func v4

---

application/api/login.py
application/common/constants.py
application/common/token.py
application/common/utils.py
application/model/models.py
application/routes.py
config.cfg
templates/email_reset_password.html

@HarshadKavathiya @lalithbachimanchi Please Review Forget Password

Forget password

---

application/api/testcase.py
application/api/testsuite.py
application/common/dqi_calculation.py
application/helper/corefunctions/ddlcheck.py
application/helper/runnerclass.py
application/helper/runnerclasshelpers.py

@HarshadKavathiya @lalithbachimanchi Please Review DQI calculation

DQI Calculation

---

application/api/group.py
application/api/project.py
application/common/constants.py
application/model/models.py
application/routes.py

Group API and Added Is_org_user key in Project GET API

---

application/api/user_management.py
application/common/constants.py
application/model/models.py
application/routes.py

POST call for adding UserOrgRole and UserProjectRole

---

application/api/user_management.py
application/common/constants.py

GET User Role API

---

application/api/checkconnection.py
application/api/dbdetail.py
application/common/createdbdetail.py

2. changed check connection api

1. changed db detail api

---

application/api/login.py

@HarshadKavathiya please review

Added logic to verify for already registered users

---

application/common/dbconnect.py

@HarshadKavathiya please review and merge it.

Added logic to split host and port from hostname for postgresql db connection

---

application/api/menu.py
application/common/constants.py
application/helper/permission_check.py
application/model/models.py

Added Menu Table, super user column in user table, helper method to check authorization

---

application/api/role.py

Changed old variable references

---

application/api/dbdetail.py
application/common/constants.py

@HarshadKavathiya Please do review

Testing dbdetails

---

spark/spark_dw.py

@harshad please merge this,reason for datavalidation not working

changed sqlserver - > mssql in sparkdw file

---

application/api/testsuite.py

@HarshadKavathiya there was issue in upload and execute need to fix it.

revamp upload and execute logic

---

application/api/dbdetail.py

@HarshadKavathiya Please Review

Fixing bugs in db details put call

---

application/api/testsuite.py
application/common/constants.py
application/common/utils.py
application/routes.py

@HarshadKavathiya Please do Review

Edittestsuite

---

application/api/data_quality_index.py
application/api/menu.py
application/common/common_exception.py
application/helper/permission_check.py
application/routes.py

Common Exception in Routes File

---

application/api/dbdetail.py
application/api/testcase.py
application/api/testsuite.py
application/common/constants.py
application/model/models.py
application/routes.py
config.cfg

@HarshadKavathiya Please do review for Add test suite manually and delete test case.

Add testsuite

---

application/api/data_quality_index.py

@harshad added logic for dqi- charts order by pattern suresh provided

Added logic for dqi charts in Order

---

application/api/testsuite.py
application/common/constants.py
application/helper/uploadfiledb.py
config.cfg

@HarshadKavathiya ,Please do review for unique test suite name

Unique test suite name

---

application/api/dbdetail.py
application/api/testcase.py
application/common/constants.py

@HarshadKavathiya ,Please do review edit test case api

Edit test case api

---

application/api/user_management.py
application/common/common_exception.py
application/common/constants.py
application/routes.py

Migrated User Management APIs

---

application/api/dbdetail.py
application/common/constants.py

@HarshadKavathiya please do review for edit db details api

Edit db details api

---

application/api/testsuite.py

@HarshadKavathiya Added Exception Handling and User Mgmt for Upload Suite<POST>, Execute Job<POST>

Develop exception handling aug23

---

application/api/connectiondetail.py
application/common/constants.py
application/helper/connectiondetails.py

@HarshadKavathiya Please do review for case deatil api

case detail api

---

application/api/connectiondetail.py
application/api/testcase.py
application/api/testsuite.py
application/common/constants.py
application/common/createdbdetail.py

Api Mgmt for TestSuite,Select Connection,Test-Case-Job External

---

application/api/dbdetail.py
application/api/testcase.py
application/api/testsuite.py
application/common/constants.py
application/common/utils.py

@HarshadKavathiya  Please do review for create new test api

Edit create new test suite api

---

application/api/dbdetail.py

@HarshadKavathiya Please do review change variable name

change variable

---

application/api/checkconnection.py
application/api/dbdetail.py
application/common/constants.py
application/helper/connection_check.py

@HarshadKavathiya please do review for edit check connection api

edit check connection api

---

application/api/testsuite.py
application/common/constants.py

@HarshadKavathiya Please do review for edit test suite put api

edit test suite put api

---

application/api/role.py

@HarshadKavathiya Please do review for edit role api

Edit role api

---

acciom_ui/src/components/ManageConnection.js
acciom_ui/src/components/ManageConnectionSelect.js
acciom_ui/src/components/ViewTestCase.js
acciom_ui/src/containers/AddDbDetails.js
acciom_ui/src/containers/TestSuiteUpload.js
acciom_ui/src/reducers/testSuiteUploadReducer.js

UI Defects

---

application/common/returnlog.py
application/helper/connectiondetails.py
application/helper/uploadfiledb.py

1)upload file logic
2)test_case_detail
3) test_case_log api

changes in

---

application/api/testcase.py
application/common/constants.py
application/common/runbysuiteid.py
application/helper/corefunctions/countcheck.py
application/helper/corefunctions/duplicate.py
application/helper/corefunctions/nullcheck.py

@HarshadKavathiya issue related to run job ,plz merge

Run Job Issue

---

acciom_ui/src/actions/testSuiteListActions.js
acciom_ui/src/components/ViewTestCase.js
acciom_ui/src/containers/AddDbDetails.js
acciom_ui/src/containers/TestSuiteList.js
acciom_ui/src/reducers/testSuitesReducer.js

Add DB Details Button, Edit DB & Edit Test Case in Test Suite List.

DB and test suit defects

---

application/api/dbdetail.py

@HarshadKavathiya Please do review

space validation on post call

---

acciom_ui/src/components/AuthToken.js
acciom_ui/src/components/ManageConnection.js
acciom_ui/src/components/ManageConnectionInputs.js
acciom_ui/src/components/ManageConnectionSelect.js
acciom_ui/src/components/SwitchProject.js
acciom_ui/src/containers/EditUserRoles.js
acciom_ui/src/containers/RoleListItemContainer.js
acciom_ui/src/containers/Startup.js
acciom_ui/src/containers/TestSuiteList.js
acciom_ui/src/containers/TestSuiteUpload.js
acciom_ui/src/containers/UserManagement.js
acciom_ui/src/containers/ViewDbDetails.js
acciom_ui/src/css/Db-ui-styles.css
acciom_ui/src/css/styles.css

@HarshadKavathiya please review my code and merge

Dbconnection styling

---

application/api/data_quality_index.py
application/api/user_management.py
application/common/constants.py

@HarshadKavathiya Plaese do review for change keys of dqi history and order of user list

change keys of dqi history and order of user list

---

application/api/checkconnection.py
application/api/connectiondetail.py
application/api/dbdetail.py
application/api/testcase.py
application/api/testsuite.py
application/common/constants.py
application/helper/connection_check.py

@HarshadKavathiya  Please do review,remove success message

remove success message

---

application/api/data_quality_index.py
application/common/constants.py

@HarshadKavathiya  Please do review of change label of average dqi

change label of average dqi

---

application/common/dqi_calculation.py

dqi testing

---

application/common/constants.py
application/helper/corefunctions/duplicate.py
application/helper/corefunctions/nullcheck.py

added result, table_name and total count in nullcheck,duplicate

---

application/api/user_management.py
application/common/constants.py

@HarshadKavathiya  Please do review for change in user role post api

change user role post api

---

application/api/project.py
application/helper/runnerclasshelpers.py

@HarshadKavathiya Please do review for change in Project GET API

Edit project get api

---

application/api/data_quality_index.py

dqi values round to 2

---

application/api/dbdetail.py
application/common/constants.py

@HarshadKavathiya Please do review for space validation for db name

add space validation for dbname

---

application/api/dbdetail.py
application/api/testcase.py
application/common/common_exception.py
application/common/constants.py
application/routes.py

@HarshadKavathiya Please do review for validating maximum character in dbdetails

Validating maximum characters in dbdetails

---

application/api/organization.py
application/common/constants.py
application/common/response.py
application/routes.py

@HarshadKavathiya Please do review for change in organization get api

change in get organization

---

application/common/constants.py
application/helper/corefunctions/ddlcheck.py

@HarshadKavathiya  Please do review for add headings to ddl check result

Add headings to ddl  check result

---

application/api/project.py
application/api/role.py
application/api/testcase.py
application/api/testsuite.py

@HarshadKavathiya Please do review for solving todo tasks

Solve TO DO 

---

application/api/project.py
application/api/user_management.py
application/common/constants.py

Develop project del

---

application/api/query_analyser.py

changing the parameters to body of the request

changing the parameters to body of the request

---

application/helper/exportTestcaselog.py

@HarshadKavathiya  Please do review for export bug fixrers

Export bug fixers

---

application/api/project.py
application/common/constants.py

@HarshadKavathiya  Please do review for change in put and delete API

change in put and delete

---

application/api/user_management.py
application/common/constants.py

@HarshadKavathiya  Please do review for making constant as empty string

make constant as empty string

---

application/api/user_management.py
application/routes.py

@HarshadKavathiya  Please do review for get all permissions

get all permissions

---

application/api/user_management.py

@HarshadKavathiya  Please do review for add verification for set org project default api

add verification to set default api

---

application/api/connectiondetail.py
application/helper/connectiondetails.py

changed api

---

application/helper/connectiondetails.py

@HarshadKavathiya plz merge it

API CHANGE

---

application/api/query_analyser.py
application/common/constants.py
application/helper/corefunctions/queryexecution.py
application/helper/runnerclasshelpers.py

@HarshadKavathiya Please do Review for delete api for query analyser

delete api for query analyser
